# Generated by Django 5.0.6 on 2024-05-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
