# Generated by Django 5.0.6 on 2024-05-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_category_alter_job_description_and_more'),
        ('jobs', '0003_remove_job_is_available_alter_job_category_and_more'),
    ]

    operations = [
    ]
