# Generated by Django 5.0.6 on 2024-05-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_merge_20240516_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
