# Generated by Django 5.0.6 on 2024-05-17 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Unknown Company', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='due_date',
            field=models.DateField(default=datetime.date(2000, 12, 12)),
        ),
    ]
